export const exams = [
  {
    id: 1,
    exam: "A.N.C.A ANTI-NEUTROFILOS(ANCA)-LIMA",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 7,
  },
  {
    id: 2,
    exam: "acido folico",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 70,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 3,
    exam: "aga y electrolitos",
    sample: "sangre arterial ó venosa",
    method: "gasometria",
    price: 80,
    tube: "jeringa especial con heparina",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 4,
    exam: "alfafeto proteina(afp)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 hras",
    time: 1,
  },
  {
    id: 5,
    exam: "amilasa serica",
    sample: "suero",
    method: "cinetico",
    price: 15,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 6,
    exam: "ANTI DNA-DS(LIMA)",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price: 140,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 7,
    exam: "ANTI-CCP(PEPTIDO CICLICO CITRUNILADO)IGG-LIMA",
    sample: "suero",
    method: "elisa",
    price: 200,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 8,
    exam: "ANTICUERPOS ANTINUCLEARES(ANA)-LIMA",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 9,
    exam: "ANTICUERPOS ANTITIROIDES-LIMA",
    sample: "suero",
    method: "ECLIA / MODULAR PE",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 10,
    exam: "ANTIGENO CARCINO EMBRIONARIO(CEA)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 45,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 11,
    exam: "CA 125(ovario)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 48,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 12,
    exam: "CA 15-3(mama)-lima",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 170,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 13,
    exam: "glucosa",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 5,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 14,
    exam: "colesterol total",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 5,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 15,
    exam: "trigliceridos",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 7,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 16,
    exam: "hemograma automatizada",
    sample: "sangre total",
    method: "citometría de flujo",
    price: 15,
    tube: "tapa lila",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 17,
    exam: "hemoglobina",
    sample: "sangre total",
    method: "manual",
    price: 5,
    tube: "tapa lila",
    preanalitic: "no requiere ayuno",
    time: 1,
  },
  {
    id: 18,
    exam: "ex. completo de orina",
    sample: "orina ocasional",
    method: "manual",
    price: 5,
    tube: "frasco tapa rojo no esteril",
    preanalitic: "se recomienda primera orina de la mañana chorro intermedio ",
    time: 1,
  },
  {
    id: 19,
    exam: "hemoglobina glicosilada",
    sample: "sangre total",
    method: "inmunoflorescencia",
    price: 40,
    tube: "tapa lila",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 20,
    exam: "tsh",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 21,
    exam: "t4 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 22,
    exam: "t3 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 23,
    exam: "perfil lipidico",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 24,
    exam: "perfil hepatico",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 30,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 25,
    exam: "perfil renal simple",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 17,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 26,
    exam: "perfil tiroideo(tsh-t4 libre-t3 libre)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 115,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 27,
    exam: "tsh",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 35,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 28,
    exam: "t4 libre)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 29,
    exam: "t3 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 30,
    exam: "prolactina",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 31,
    exam: "lh",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 38,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 32,
    exam: "fsh",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 38,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 33,
    exam: "testosterona total",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 34,
    exam: "testosterona libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 55,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 35,
    exam: "estradiol total-e2",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 36,
    exam: "progesterona",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 37,
    exam: "troponina i",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 50,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 38,
    exam: "lipasa",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 39,
    exam: "ggt-gamma-glutamil",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 40,
    exam: "calcio serico",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 7,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 41,
    exam: "acido urico",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 7,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 42,
    exam: "perfil de coagulacion",
    sample: "plasma con citrato de sodio",
    method: "coagulometria",
    price: 25,
    tube: "tapa celeste",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 43,
    exam: "grupo sanguineo",
    sample: "sangre total",
    method: "manual",
    price: 5,
    tube: "tapa lila",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 44,
    exam: "heces seriado x 3 veces",
    sample: "heces",
    method: "microscopia",
    price: 15,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 45,
    exam: "heces simple x 1 veces",
    sample: "heces",
    method: "microscopia",
    price: 5,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 46,
    exam: "heces coprofuncional",
    sample: "heces",
    method: "microscopia",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 47,
    exam: "metodo de faust-heces concentrada",
    sample: "heces",
    method: "microscopia",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 48,
    exam: "metodo de baermann-strongyloides",
    sample: "heces",
    method: "microscopia",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 49,
    exam: "reaccion inflamatoria-heces",
    sample: "heces",
    method: "microscopia",
    price: 5,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 50,
    exam: "thevenon-heces-sangre oculta",
    sample: "heces",
    method: "manual",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 51,
    exam: "tolerancia a la glucosa",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 30,
    tube: "tapa rojo ó amarillo",
    preanalitic:
      "MUESTRAS TOMADAS:BASAL 30, 60, 120, 180 MINUTOS. SALVO OTRA INDICACION DEL MEDICO. ADULTOS: 75 GR. glucosa anhidra Y  EMBARAZADAS SÓLO ENTRE 24 A 28 SEMANAS. REVISAR ORDEN MEDICA: 100 GR glucosa anhidra .. DISOLVER EN 250 - 300 ML DE AGUA",
    time: 1,
  },
  {
    id: 52,
    exam: "tericulocitos recuento",
    sample: "sangre total con edta",
    method: "AZUL BRILLANTE DE CRESIL / MANUAL",
    price: 15,
    tube: "tapa lila",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 53,
    exam: "lamina periferica",
    sample: "sangre total con edta",
    method: "-/-",
    price: 25,
    tube: "tapa lila mas lamina",
    preanalitic:
      "TODA REFERENCIA: DEBE REALIZAR EXTENDIDO DE SANGRE SOBRE LÁMINA PORTAOBJETOS. ADEMÁS ENVIAR TUBO TAPA LILA.",
    time: 1,
  },
  {
    id: 54,
    exam: "recuento de plaquetas",
    sample: "sangre total con edta",
    method: "microscopia",
    price: 10,
    tube: "tapa lila mas lamina",
    preanalitic:
      "TODA REFERENCIA: DEBE REALIZAR EXTENDIDO DE SANGRE SOBRE LÁMINA PORTAOBJETOS. ADEMÁS ENVIAR TUBO TAPA LILA.",
    time: 1,
  },
  {
    id: 53,
    exam: "espermatograma",
    sample: "semen",
    method: "microscopia/manual",
    price: 40,
    tube: "tapa lila mas lamina",
    preanalitic:
      "SE REQUIERE DE 3 A 5 DÍAS DE ABSTINENCIA. SE RECEPCIONAN LUNES A SÁBADO DE 7 AM A 11 AM. EN CASO DE FERIADO NO RECIBIR UN DÍA ANTES. INDICAR FECHA DE VASECTOMÍA SI CORRESPONDE. NO APLICA LOS SÁBADOS, DOMINGOS, FERIADOS NI DÍAS PREVIOS A FERIADOS.",
    time: 2,
  },
  {
    id: 54,
    exam: "insulina",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 55,
    exam: "dimero d",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 56,
    exam: "ferritina",
    sample: "suero",
    method: "elisa",
    price: 35,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 57,
    exam: "procalcitonina",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 58,
    exam: "inmunoglobulina e-ige",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 59,
    exam: "cortisol am",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 50,
    tube: "tapa rojo ó amarillo",
    preanalitic:
      "MUESTRA TOMADA ENTRE 8:00 Y 9:00 AM. SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 60,
    exam: "cortisol pm",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 50,
    tube: "tapa rojo ó amarillo",
    preanalitic:
      "MUESTRA TOMADA ENTRE 8:00 Y 9:00 AM. SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 61,
    exam: "coombs directo",
    sample: "sangre total",
    method: "HEMAGLUTINACION / MANUAL",
    price: 25,
    tube: "tapa lila",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 62,
    exam: "coombs indirecto",
    sample: "suero",
    method: "HEMAGLUTINACION / MANUAL",
    price: 30,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 63,
    exam: "vih 4ta generacion",
    sample: "suero",
    method: "elisa",
    price: 45,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 64,
    exam: "vih prueba rapida",
    sample: "suero",
    method: "cromatografia",
    price: 20,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 65,
    exam: "serologia cualitativa rpr-sifilis",
    sample: "suero",
    method: "floculacion/manual",
    price: 15,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 66,
    exam: "serologia semi-cuantitativa rpr-sifilis",
    sample: "suero",
    method: "floculacion/manual",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
];
