export const exams = [
  {
    id: 1,
    exam: "A.N.C.A ANTI-NEUTROFILOS(ANCA)-LIMA",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 7,
  },
  {
    id: 2,
    exam: "acido folico",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 70,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 3,
    exam: "aga y electrolitos (a domicilio)",
    sample: "sangre arterial ó venosa",
    method: "gasometria",
    price: 80,
    tube: "jeringa especial con heparina",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 4,
    exam: "alfafeto proteina(afp)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 hras",
    time: 1,
  },
  {
    id: 5,
    exam: "amilasa serica",
    sample: "suero",
    method: "cinetico",
    price: 20,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 6,
    exam: "ANTI DNA-DS(LIMA)",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price: 140,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 7,
    exam: "ANTI-CCP(PEPTIDO CICLICO CITRUNILADO)IGG-LIMA",
    sample: "suero",
    method: "elisa",
    price: 200,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 8,
    exam: "ANTICUERPOS ANTINUCLEARES(ANA)-LIMA",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 9,
    exam: "ANTICUERPOS ANTITIROIDES-LIMA",
    sample: "suero",
    method: "ECLIA / MODULAR PE",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 10,
    exam: "ANTIGENO CARCINO EMBRIONARIO(CEA)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 45,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 11,
    exam: "CA 125(ovario)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 48,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 12,
    exam: "CA 15-3(mama)-lima",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 170,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 7,
  },
  {
    id: 13,
    exam: "glucosa",
    sample: "suero",
    method: "colorimetrico",
    price: 5,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 14,
    exam: "colesterol total",
    sample: "suero",
    method: "colorimetrico",
    price: 5,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 15,
    exam: "trigliceridos",
    sample: "suero",
    method: "colorimetrico",
    price: 7,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 16,
    exam: "hemograma automatizada",
    sample: "sangre total",
    method: "citometría de flujo",
    price: 15,
    tube: "tapa lila",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 17,
    exam: "hemoglobina",
    sample: "sangre total",
    method: "manual",
    price: 5,
    tube: "tapa lila",
    preanalitic: "no requiere ayuno",
    time: 1,
  },
  {
    id: 18,
    exam: "ex. completo de orina(eco)",
    sample: "orina ocasional",
    method: "manual",
    price: 5,
    tube: "frasco tapa rojo no esteril",
    preanalitic: "se recomienda primera orina de la mañana chorro intermedio ",
    time: 1,
  },
  {
    id: 19,
    exam: "hemoglobina glicosilada(HbA1c)",
    sample: "sangre total",
    method: "inmunoflorescencia",
    price: 40,
    tube: "tapa lila",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 20,
    exam: "tsh",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 21,
    exam: "t4 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 22,
    exam: "t3 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 23,
    exam: "perfil lipidico",
    sample: "suero",
    method: "colorimetrico",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 24,
    exam: "perfil hepatico",
    sample: "suero",
    method: "cinetico/colorimetrico",
    price: 30,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 25,
    exam: "perfil renal simple",
    sample: "suero",
    method: "cinetico/colorimetrico",
    price: 17,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 26,
    exam: "perfil tiroideo(tsh-t4 libre-t3 libre)",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 115,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 27,
    exam: "CREATINFOSFOQUINASA (CPK TOTAL)",
    sample: "suero",
    method: "cinetico",
    price: 35,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 28,
    exam: "t4 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 29,
    exam: "t3 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 30,
    exam: "prolactina",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 31,
    exam: "lh",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 38,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 32,
    exam: "fsh",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 38,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 33,
    exam: "testosterona total",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 34,
    exam: "testosterona libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 55,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 35,
    exam: "estradiol total-e2",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 36,
    exam: "progesterona",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 37,
    exam: "troponina i",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 50,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 38,
    exam: "lipasa",
    sample: "suero",
    method: "cinetico",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 39,
    exam: "ggt-gamma-glutamil",
    sample: "suero",
    method: "cinetico",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 40,
    exam: "calcio serico",
    sample: "suero",
    method: "colorimetrico",
    price: 7,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 41,
    exam: "acido urico",
    sample: "suero",
    method: "colorimetrico",
    price: 7,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 42,
    exam: "perfil de coagulacion(tp-ttpa-tc-ts)",
    sample: "plasma/citrato",
    method: "coagulometria",
    price: 25,
    tube: "tapa celeste",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 43,
    exam: "grupo sanguineo",
    sample: "sangre total",
    method: "manual",
    price: 7,
    tube: "tapa lila",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 44,
    exam: "heces seriado x 3 veces",
    sample: "heces",
    method: "microscopia",
    price: 15,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 45,
    exam: "heces simple x 1 veces",
    sample: "heces",
    method: "microscopia",
    price: 5,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 46,
    exam: "heces coprofuncional",
    sample: "heces",
    method: "microscopia",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 47,
    exam: "metodo de faust-heces concentrada",
    sample: "heces",
    method: "microscopia",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 48,
    exam: "metodo de baermann-strongyloides",
    sample: "heces",
    method: "microscopia",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 49,
    exam: "reaccion inflamatoria-heces",
    sample: "heces",
    method: "microscopia",
    price: 5,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 50,
    exam: "thevenon-heces-sangre oculta",
    sample: "heces",
    method: "manual",
    price: 12,
    tube: "frasco tapa rosca",
    preanalitic:
      "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: 1,
  },
  {
    id: 51,
    exam: "tolerancia a la glucosa",
    sample: "suero",
    method: "bioquimica automatizada",
    price: 30,
    tube: "tapa rojo ó amarillo",
    preanalitic:
      "MUESTRAS TOMADAS:BASAL 30, 60, 120, 180 MINUTOS. SALVO OTRA INDICACION DEL MEDICO. ADULTOS: 75 GR. glucosa anhidra Y  EMBARAZADAS SÓLO ENTRE 24 A 28 SEMANAS. REVISAR ORDEN MEDICA: 100 GR glucosa anhidra .. DISOLVER EN 250 - 300 ML DE AGUA",
    time: 1,
  },
  {
    id: 52,
    exam: "tericulocitos recuento",
    sample: "sangre total con edta",
    method: "AZUL BRILLANTE DE CRESIL / MANUAL",
    price: 15,
    tube: "tapa lila",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 53,
    exam: "lamina periferica",
    sample: "sangre total con edta",
    method: "-/-",
    price: 25,
    tube: "tapa lila mas lamina",
    preanalitic:
      "TODA REFERENCIA: DEBE REALIZAR EXTENDIDO DE SANGRE SOBRE LÁMINA PORTAOBJETOS. ADEMÁS ENVIAR TUBO TAPA LILA.",
    time: 1,
  },
  {
    id: 54,
    exam: "recuento de plaquetas",
    sample: "sangre total con edta",
    method: "microscopia",
    price: 10,
    tube: "tapa lila mas lamina",
    preanalitic:
      "TODA REFERENCIA: DEBE REALIZAR EXTENDIDO DE SANGRE SOBRE LÁMINA PORTAOBJETOS. ADEMÁS ENVIAR TUBO TAPA LILA.",
    time: 1,
  },
  {
    id: 55,
    exam: "espermatograma",
    sample: "semen",
    method: "microscopia/manual",
    price: 40,
    tube: "frasco tapa verde esteril",
    preanalitic:
      "SE REQUIERE DE 3 A 5 DÍAS DE ABSTINENCIA. SE RECEPCIONAN LUNES A SÁBADO DE 7 AM A 11 AM. EN CASO DE FERIADO NO RECIBIR UN DÍA ANTES. INDICAR FECHA DE VASECTOMÍA SI CORRESPONDE. NO APLICA LOS SÁBADOS, DOMINGOS, FERIADOS NI DÍAS PREVIOS A FERIADOS.",
    time: 2,
  },
  {
    id: 56,
    exam: "insulina",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 57,
    exam: "dimero d",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 58,
    exam: "ferritina",
    sample: "suero",
    method: "elisa",
    price: 35,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 59,
    exam: "procalcitonina",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 60,
    exam: "inmunoglobulina e-ige",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "se sugiere ayuno de 8 hras",
    time: 1,
  },
  {
    id: 61,
    exam: "cortisol am",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 50,
    tube: "tapa rojo ó amarillo",
    preanalitic:
      "MUESTRA TOMADA ENTRE 8:00 Y 9:00 AM. SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 62,
    exam: "cortisol pm",
    sample: "suero",
    method: "quimioluminiscencia",
    price: 50,
    tube: "tapa rojo ó amarillo",
    preanalitic:
      "MUESTRA TOMADA ENTRE 8:00 Y 9:00 AM. SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 63,
    exam: "coombs directo",
    sample: "sangre total",
    method: "HEMAGLUTINACION / MANUAL",
    price: 25,
    tube: "tapa lila",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 64,
    exam: "coombs indirecto",
    sample: "suero",
    method: "HEMAGLUTINACION / MANUAL",
    price: 30,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 65,
    exam: "vih 4ta generacion(elisa)",
    sample: "suero",
    method: "elisa",
    price: 45,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 66,
    exam: "vih prueba rapida",
    sample: "suero",
    method: "cromatografia",
    price: 20,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 67,
    exam: "serologia cualitativa rpr-sifilis",
    sample: "suero",
    method: "floculacion/manual",
    price: 15,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 68,
    exam: "serologia semi-cuantitativa rpr-sifilis",
    sample: "suero",
    method: "floculacion/manual",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 69,
    exam: "vitamina b12",
    sample: "suero",
    method: "elisa",
    price: 70,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 70,
    exam: "cpk-mb",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 45,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 71,
    exam: "cpk-mb",
    sample: "suero",
    method: "cinetico",
    price: 45,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 72,
    exam: "psa libre",
    sample: "suero",
    method: "elisa",
    price: 55,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 73,
    exam: "psa total",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 74,
    exam: "variante du",
    sample: "sangre total",
    method: "HEMAGLUTINACION / MANUAL",
    price: 20,
    tube: "tapa lila",
    preanalitic: "no necesita ayuno previo.",
    time: 1,
  },
  {
    id: 75,
    exam: "CHLAMYDIA TRACHOMATIS IGG-IGM",
    sample: "suero",
    method: "elisa",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 76,
    exam: "ANTICOAGULANTE LUPICO ",
    sample: "suero",
    method: "COAGULOMETRICO",
    price: 130,
    tube: "tapa celeste",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "5 a 7",
  },
  {
    id: 77,
    exam: "ANTI CARDIOLIPINA IGA-IGG-IGM",
    sample: "suero",
    method: "ELISA",
    price: 270,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "5 a 7",
  },
  {
    id: 78,
    exam: "BETA 2 GLICOPROTEINA I IGG-IGM",
    sample: "suero",
    method: "ELISA",
    price: 232,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "5 a 7",
  },
  {
    id: 79,
    exam: "tiempo de protrombina(tp) mas inr",
    sample: "plasma/citrato",
    method: "coagulometria",
    price: 10,
    tube: "tapa celeste",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 80,
    exam: "tiempo de tromboplastina parcial activada(ttpa)",
    sample: "plasma/citrato",
    method: "coagulometria",
    price: 10,
    tube: "tapa celeste",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 81,
    exam: "tiempo de tromboplastina parcial activada(ttpa)",
    sample: "plasma/citrato",
    method: "coagulometria",
    price: 10,
    tube: "tapa celeste",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 82,
    exam: "microalbuminuria",
    sample: "orina simple",
    method: "inmunoflorescencia",
    price: 40,
    tube: "frasco tapa rosca",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 83,
    exam: "helicobacter pylori igg",
    sample: "suero",
    method: "inmunocromatografia",
    price: 30,
    tube: "tapa rojo/amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 84,
    exam: "reticulocitos recuento",
    sample: "sangre total",
    method: "microscopia manual",
    price: 15,
    tube: "tapa lila",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 85,
    exam: "constantes corpusculares",
    sample: "sangre total",
    method: "manual",
    price: 12,
    tube: "tapa lila",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 86,
    exam: "OXIUROS (TEST DE GRAHAM)",
    sample: "CINTA ADHESIVA",
    method: "microscopia/manual",
    price: 7,
    tube: "lamina",
    preanalitic: "LIMPIEZA DE LA ZONA ANAL ANTES DE ACOSTARSE. HORA DE TOMA DE MUESTRA : 5:00 A 6:00 AM MATERIALES: CINTA ADHESIVA TRANSPARENTE (1 A 2 X 10 A 12 CM) + LÁMINA PORTAOJETOS (LABORATORIO) PROCEDIMIENTO: COLOCAR AL PCTE. BOCA ABAJO EN LA POSICIÓN QUE PERMITA QUE LAS NALGAS SE SEPAREN PARA COLOCAR LA CINTA EN EL ANO ( AL CENTRO Y ALREDEDOR Ó PERI-ANAL) Y LUEGO COLOCARLO EN LA LAMINA.",
    time: 1,
  },
  {
    id: 87,
    exam: "ACIDOS BILIARES TOTALES",
    sample: "suero",
    method: "ELISA",
    price: 150,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "5 a 7",
  },
  {
    id: 88,
    exam: "HORMONA ANTI MULLERIANA (AMH/MIS)",
    sample: "suero",
    method: "ECLIA / COBAS 8000",
    price: 300,
    tube: "tapa rojo ó amarillo",
    preanalitic: "NO REQUIERE AYUNO ANTES DE LA PRUEBA.",
    time: "5 a 7",
  },
  {
    id: 89,
    exam: "ANTI CORE",
    sample: "suero",
    method: "CLIA",
    price: 45,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 90,
    exam: "hepatitis b-antigeno de superficie (hbsag)",
    sample: "suero",
    method: "inmunocromatografia",
    price: 20,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 91,
    exam: "hepatitis a (igg)",
    sample: "suero",
    method: "inmunocromatografia",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 92,
    exam: "hepatitis c (hcv)",
    sample: "suero",
    method: "inmunocromatografia",
    price: 25,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 93,
    exam: "herpes 1/2 (igg-igm)",
    sample: "suero",
    method: "inmunocromatografia",
    price: 75,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 94,
    exam: "urea",
    sample: "suero",
    method: "cinetico",
    price: 5,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 95,
    exam: "creatinina",
    sample: "suero",
    method: "cinetico",
    price: 5,
    tube: "tapa rojo ó amarillo",
    preanalitic: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: 1,
  },
  {
    id: 96,
    exam: "proteinuria orina de 24 h",
    sample: "orina de 24 horas",
    method: "colorimetrico",
    price: 20,
    tube: "galorena",
    preanalitic: "NO CONSUMIR ALCOHOL DURANTE TODO EL PROCESO DE RECOLECCIÓN. RECOLECCIÓN: ELIMINAR LA 1RA ORINA DE LA MAÑANA, RECOLECTAR DESDE LA 2DA EN ADELANTE HASTA EL DÍA SIGUIENTE DONDE SE RECOLECTA LA 1RA ORINA. NO ELIMINAR NI BOTAR NINGUNA MUESTRA DE ORINA. ANOTAR FECHA, INICIO Y TERMINO DE LA RECOLECCIÓN.",
    time: 1,
  },
  {
    id: 97,
    exam: "depuracion de creatinina en orina de 24 h",
    sample: "orina de 24 horas/suero",
    method: "cinetico",
    price: 20,
    tube: "galorena/tubo rojo o amarillo",
    preanalitic: "NO CONSUMIR ALCOHOL DURANTE TODO EL PROCESO DE RECOLECCIÓN. RECOLECCIÓN: ELIMINAR LA 1RA ORINA DE LA MAÑANA, RECOLECTAR DESDE LA 2DA EN ADELANTE HASTA EL DÍA SIGUIENTE DONDE SE RECOLECTA LA 1RA ORINA. NO ELIMINAR NI BOTAR NINGUNA MUESTRA DE ORINA. ANOTAR FECHA, INICIO Y TERMINO DE LA RECOLECCIÓN.",
    time: 1,
  },
  {
    id: 98,
    exam: "hcg cuantificado",
    sample: "suero",
    method: "elisa",
    price: 40,
    tube: "tubo rojo o amarillo",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 99,
    exam: "hcg cualitativo",
    sample: "suero",
    method: "cromatografia",
    price: 10,
    tube: "tubo rojo o amarillo",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 100,
    exam: "hierro serico",
    sample: "suero",
    method: "cinetico",
    price: 38,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 101,
    exam: "leptospira igm",
    sample: "suero",
    method: "elisa",
    price: 45,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 102,
    exam: "fosforo",
    sample: "suero",
    method: "cinetico",
    price: 35,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 103,
    exam: "magnesio",
    sample: "suero",
    method: "cinetico",
    price: 35,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 104,
    exam: "urocultivo",
    sample: "orina simple",
    method: "CULTIVO / MICROSCOPIA",
    price: 22,
    tube: "frasco esteril",
    preanalitic: "COLECTAR LA MUESTRA EN FRASCO ESTÉRIL. NO ANTIBIOTICOS 03 DIAS PREVIOS AL EXAMEN. HIGIENE PREVIA DE LOS GENITALES. RECOLECTAR 1RA ORINA DE LA MAÑANA (ELIMINANDO EL 1ER CHORRO) Y REMITIR LA MUESTRA LO ANTES POSIBLE AL LABORATORIO (O MANTENER EN REFRIGERACIÓN 2 a 8°C HASTA SU ENVÍO)",
    time: 4,
  },
  {
    id: 105,
    exam: "proteina c reactiva (pcr cuantificado)",
    sample: "suero",
    method: "inmunoflorescencia",
    price: 30,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 106,
    exam: "proteina c reactiva (pcr cualitativo)",
    sample: "suero",
    method: "turbidimetria",
    price: 12,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 107,
    exam: "factor reumatoideo (fr cualitativo)",
    sample: "suero",
    method: "turbidimetria",
    price: 12,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 108,
    exam: "antiestreptolisina (aso cualitativo)",
    sample: "suero",
    method: "turbidimetria",
    price: 12,
    tube: "tubo rojo o amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 109,
    exam: "hematocrito hto",
    sample: "sangre total",
    method: "manual",
    price: 5,
    tube: "tubo lila",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 110,
    exam: "bilirrubinas totales y fraccionadas",
    sample: "suero",
    method: "colorimetrico",
    price: 15,
    tube: "tubo rojo / amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 111,
    exam: "aglutinaciones febriles",
    sample: "suero",
    method: "aglutinacion/manual",
    price: 15,
    tube: "tubo rojo / amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 112,
    exam: "electrolitos sericos (cl, na, k)",
    sample: "suero",
    method: "potenciometria",
    price: 45,
    tube: "tubo rojo / amarillo",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 113,
    exam: "aga electrolitos-hrp",
    sample: "sangre arterial",
    method: "potenciometria",
    price: 60,
    tube: "jeringa con heparina",
    preanalitic: "se recomienda ayuno de 8 horas",
    time: 1,
  },
  {
    id: 114,
    exam: "COCAINA PBC (ORINA SIMPLE) - CUALITATIVO",
    sample: "orina simple",
    method: "INMUNOCROMATOGRAFIA",
    price: 25,
    tube: "FRASCO ORINA",
    preanalitic: "NO REQUIERE AYUNO Y/O PREPARACIÓN PREVIA. NOTA: ES RESPONSABILIDAD DE LA REFERENCIA; IDENTIFICAR Y CONSTATAR QUE LA ORINA PERTENECE AL PACIENTE. NO HABER INGERIDO MATE DE COCA 24 HORAS ANTES DEL EXAMEN. NO CONSUMIR MEDICACIÓN DEL TIPO DE ANTINFLAMATORIOS, POR LO MENOS 48 HORAS ANTES DEL EXAMEN.",
    time: 1,
  },
  {
    id: 115,
    exam: "MARIHUANA THC (ORINA SIMPLE) - CUALITATIVO",
    sample: "orina simple",
    method: "INMUNOCROMATOGRAFIA / MANUAL",
    price: 25,
    tube: "FRASCO ORINA",
    preanalitic: "NO REQUIERE AYUNO Y/O PREPARACIÓN PREVIA. EL PACIENTE DEBERA PRESENTARSE CON DNI EN EL CASO DE MENORES DE EDAD CON LA PERSONA RESPONSABLE CON DNI Y FIRMAR FORMATO DE CONSENTIMIENTO PARA LA PRUEBA Y COLOCAR SU HUELLA DIGITAL, MUESTRA > 20 ML. ORINA REFRIGERADO. NOTA: ES RESPONSABILIDAD DE LA REFERENCIA; IDENTIFICAR Y CONSTATAR QUE LA ORINA PERTENECE AL PACIENTE.",
    time: 1,
  },
  {
    id: 116,
    exam: "ROTAVIRUS + ADENOVIRUS (HECES)",
    sample: "heces",
    method: "inmunocromatografia",
    price: 25,
    tube: "FRASCO CON TAPA ROSCA",
    preanalitic: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN. REFRIGERAR, EN EL CASO DE NO ENVIAR INMEDIATAMENTE.",
    time: 1,
  },
  {
    id: 117,
    exam: "bk esputo directo",
    sample: "varios",
    method: "microscopia manual",
    price: 15,
    tube: "FRASCO CON TAPA ROSCA",
    preanalitic: "NO REQUIERE DE PREPARACION PREVIA SEGÚN EL TIPO DE MUESTRA. SE SUGIERE OBTENER LA MUESTRA DE ESPUTO MUY TEMPRANO AL LEVANTARSE, ANTES DE CEPILLARSE LOS DIENTES, ANTES DE ENJUAGARSE LA BOCA Y ANTES DE INGERIR ALIMENTOS. SE DEBE RECOLECTAR LA EXPECTORACION BRONQUIAL,SIN SALIVA.",
    time: 1,
  },
  {
    id: 118,
    exam: "cultivo de secrecion vaginal",
    sample: "secrecion vaginal",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price: 25,
    tube: "MEDIO DE TRANSPORTE",
    preanalitic: "NO ANTIBIÓICOS, NI OVULOS 3 DIAS ANTES DEL EXÁMEN Y SIN ASEO PREVIO, MEDIO DE TRANSPORTE + 02 LAMINAS (FROTIS) INCLUYE : EXAMEN DIRECTO + ANTIBIOGRAMA",
    time: 4,
  },
  {
    id: 119,
    exam: "cultivo (otros)",
    sample: "varios",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price: 25,
    tube: "MEDIO DE TRANSPORTE",
    preanalitic: "NO ANTIBIÓTICOS 3 DIAS ANTES DE LA PRUEBA, NI APLICACIÓN DE ANTISEPTICAS. HERIDAS: SI ES NECESARIO LIMPIAR CON SUERO FISIOLOG. Y/O TOMAR LA MUESTRA DE LA PARTE INTERNA DE LA HERIDA. (MEDIO DE TRANSPORTE + 02 LAMINAS (FROTIS) ) ASPIRADOS: ENVIAR LA MUESTRA EN EL MISMO FRASCO O JERINGA QUE SE TOMÓ. NOTA: ES IMPORTANTE QUE SE INDIQUE LA UBICACIÓN Y TIPO DE MUESTRA QUE SE TOME EN LA ORDEN O TICKET. TIEMPO DE RESPUESTA NO SE INCLUYE DOMINGOS NI FERIADOS.",
    time: 4,
  },
  {
    id: 120,
    exam: "hemocultivo",
    sample: "sangre total",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price: 50,
    tube: "frasco hemocultivo",
    preanalitic: "DE PREFERENCIA NO ANTIBIOTICOS, 03 DIAS PREVIOS AL EXAMEN. REVISAR SOLICITUD MÉDICA Y PRECISAR LUGAR DE PUNCIÓN EN EL FRASCO DE HEMOCULTIVO. INCLUYE REMOVEDOR DE ATB, MEDIO ADULTOS: 5-10 ML DE SANGRE TOTAL (VENOSA), MEDIO PEDIATRICO: INFANTES: 1-2 ML Y NIÑOS: 3-5 ML DE SANGRE TOTAL (VENOSA).",
    time: 7,
  },
  {
    id: 121,
    exam: "test de ada",
    sample: "suero",
    method: "colorimetrico",
    price: 55,
    tube: "tubo rojo /amarillo",
    preanalitic: "no requiere ayuno previo",
    time: 1,
  },
  {
    id: 122,
    exam: "tiempo de coagulacion y tiempo de sangria",
    sample: "sangre total",
    method: "manual",
    price: 5,
    tube: "sin aditivo",
    preanalitic: "no requiere ayuna.",
    time: 1,
  },
  {
    id: 123,
    exam: "transaminasa tgo",
    sample: "suero",
    method: "cinetico",
    price: 7,
    tube: "tubo rojo / amarillo",
    preanalitic: "Se recomienda ayuno de 8 horas.",
    time: 1,
  },
  {
    id: 124,
    exam: "transaminasa tgp",
    sample: "suero",
    method: "cinetico",
    price: 7,
    tube: "tubo rojo / amarillo",
    preanalitic: "Se recomienda ayuno de 8 horas.",
    time: 1,
  },
  {
    id: 125,
    exam: "fosfatasa alcalina",
    sample: "suero",
    method: "cinetico",
    price: 7,
    tube: "tubo rojo / amarillo",
    preanalitic: "Se recomienda ayuno de 8 horas.",
    time: 1,
  },
  {
    id: 126,
    exam: "proteina totales y fraccionadas",
    sample: "suero",
    method: "colorimetrico",
    price: 15,
    tube: "tubo rojo / amarillo",
    preanalitic: "Se recomienda ayuno de 8 horas.",
    time: 1,
  },
  
];
